export const base_url = "https://backend.voltedz.com/";

export const URLS ={
    base_url  : base_url,
    ContactByCourse : base_url +  "v1/voltedzApi/admin/enquiry/addenquiry",
    contactForm : base_url +  "v1/voltedzApi/admin/contactForm/create",
    studentRegister: base_url + "v1/voltedzApi/user/student/create",
    studentLogin: base_url + "v1/voltedzApi/user/student/studentLogin",
    getStudentProfile: base_url + "v1/voltedzApi/user/student/getStudentProfile",
    getMyCourses: base_url + "v1/voltedzApi/user/myCourses/getMyCourses",
    updateStudentProfileImg: base_url + "v1/voltedzApi/user/student/updateStudentProfileImg",
    updateStudentProfile: base_url + "v1/voltedzApi/user/student/updateStudentProfile",
    studentSendOtp: base_url + "v1/voltedzApi/user/student/sendotp",
    studentCompareOtp: base_url + "v1/voltedzApi/user/student/compareotp",
    studentResetPass: base_url + "v1/voltedzApi/user/student/resetpass",
    createTicket: base_url + "v1/voltedzApi/user/ticket/create",
    getMyTickets: base_url + "v1/voltedzApi/user/ticket/getMyTickets",
    getTicketDetails: base_url + "v1/voltedzApi/user/ticket/getTicketDetails",
    sendStudentOtp: base_url + "v1/voltedzApi/user/student/sendStudentOtp",
    verifyStudentOtp: base_url + "v1/voltedzApi/user/student/verifyStudentOtp",
    getFullCourseDetails: base_url + "v1/voltedzApi/user/getCourseFullDetails/getFullCourseDetails",
    createOrder: base_url + "v1/voltedzApi/user/order/createOrder",
    updateTransaction: base_url + "v1/voltedzApi/user/order/updateTransaction",
    GetHomePage: base_url + "v1/voltedzApi/admin/homePage/getAllHomeData",
    GetAboutUsPage: base_url + "v1/voltedzApi/admin/aboutUs/getAllAboutUsData",
    getCourseMinimalDetails: base_url + "v1/voltedzApi/user/getCourseFullDetails/getCourseMinimalDetails",
    getBlogById: base_url + "/v1/voltedzApi/admin/blog/getById",
}